// =============================================================================
// WRITE PATH — the shared business logic that sits ABOVE the DAL, identical
// across backends (architect's non-negotiable §4). Notion-specific formatting
// lives in the DAL; THIS file owns the three things writes force:
//   (a) validation (delegates to bidSchema)
//   (b) canonical ID generation (bid_number YYYY-NNNN)
//   (c) version bumping + audit + void stamping
//
// BOTH write entry points (OS admin form AND, later, the calculator) must call
// THESE functions — never their own write logic — so they can't fork.
// =============================================================================

import { validateCreate, validateUpdate } from "@/lib/rules/bidSchema";

// ---- bid_number: YYYY-NNNN, counter resets each Jan 1 -----------------------
// Given the max existing sequence number for the current year, produce the next.
// The DAL supplies existingNumbersThisYear; this function owns the FORMAT + math
// so every backend generates identical IDs.
export function nextBidNumber(existingBidNumbers, now = new Date()) {
  const year = now.getFullYear();
  const prefix = `${year}-`;
  let maxSeq = 0;
  for (const bn of existingBidNumbers || []) {
    if (typeof bn === "string" && bn.startsWith(prefix)) {
      const seq = parseInt(bn.slice(prefix.length), 10);
      if (Number.isFinite(seq) && seq > maxSeq) maxSeq = seq;
    }
  }
  const next = String(maxSeq + 1).padStart(4, "0");
  return `${prefix}${next}`;
}

export function isValidBidNumber(bn) {
  return typeof bn === "string" && /^\d{4}-\d{4}$/.test(bn);
}

// ---- Assemble a CREATE payload (core fields + validated metadata) -----------
// origin: 'manual' (OS form) or 'calculator'. actor: who's doing it.
// bidNumber: generated by the caller via nextBidNumber (needs a DB read first).
export function buildCreatePayload({ metadata, origin, actor, bidNumber, now = new Date() }) {
  const clean = validateCreate(metadata);
  const ts = now.toISOString();
  return {
    ...clean,
    bidNumber,
    origin,
    version: 1,
    createdBy: actor || "unknown",
    createdAt: ts,
    modifiedBy: actor || "unknown",
    modifiedAt: ts,
    isVoided: false,
    voidedAt: null,
    voidedBy: null,
  };
}

// ---- Assemble an UPDATE payload (optimistic concurrency + version bump) ------
// expectedVersion: the version the editor loaded. The DAL must reject the write
// if the stored version != expectedVersion (someone else edited it).
export function buildUpdatePayload({ changes, actor, expectedVersion, now = new Date() }) {
  const clean = validateUpdate(changes);
  return {
    fields: {
      ...clean,
      modifiedBy: actor || "unknown",
      modifiedAt: now.toISOString(),
    },
    expectedVersion, // DAL enforces the guard, then sets version = expectedVersion + 1
  };
}

// ---- Assemble a VOID payload (never hard-delete) ----------------------------
export function buildVoidPayload({ actor, expectedVersion, now = new Date() }) {
  return {
    fields: {
      isVoided: true,
      voidedAt: now.toISOString(),
      voidedBy: actor || "unknown",
      modifiedBy: actor || "unknown",
      modifiedAt: now.toISOString(),
    },
    expectedVersion,
  };
}

// ---- Soft duplicate guard (create-time warning, not a block) ----------------
// Warn if same GC + Project Name + Bid Due Date already exists ("edit instead?").
export function findSoftDuplicate(metadata, existingBids) {
  const name = (metadata.projectName || "").trim().toLowerCase();
  const due = metadata.bidDueDate || null;
  const gcs = (metadata.gc || []).map((g) => g.toLowerCase()).sort().join("|");
  return (existingBids || []).find((b) => {
    if (b.isVoided) return false;
    const bName = (b.name || "").trim().toLowerCase();
    const bDue = b.bidDueDate || null;
    const bGcs = (b.gc || []).map((g) => g.toLowerCase()).sort().join("|");
    return bName === name && bDue === due && bGcs === gcs && name.length > 0;
  }) || null;
}
